spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
exam:
  questions:
    amount: 5
  ranking:
    password: password
